-- PostgreSQL database dump
-- 
-- \restrict XS1eEWavleW8dDepOUfdD5sbwRRKCAduzsG0baCIXXWxklj2vF8svsL0JBZHWR1

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: absence; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.absence (
    id bigint NOT NULL,
    date character varying(255),
    duree character varying(255),
    motif character varying(255),
    statut character varying(255),
    employee_id bigint,
    type_absence_conge_id bigint
);


ALTER TABLE public.absence OWNER TO postgres;

--
-- Name: absence_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.absence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agence; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.agence (
    id bigint NOT NULL,
    actif boolean,
    adresse character varying(255),
    code_agence character varying(255),
    email character varying(255),
    nom_agence character varying(255),
    telephone character varying(255),
    ville character varying(255)
);


ALTER TABLE public.agence OWNER TO postgres;

--
-- Name: agence_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.agence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bareme_iuts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bareme_iuts (
    id bigint NOT NULL,
    abattement_forfaitaire double precision,
    actif boolean,
    code_tranche character varying(255),
    taux_imposition double precision,
    tranche_max double precision,
    tranche_min double precision
);


ALTER TABLE public.bareme_iuts OWNER TO postgres;

--
-- Name: bareme_iuts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bareme_iuts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bareme_iuts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorie (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255),
    taux_abattement double precision
);


ALTER TABLE public.categorie OWNER TO postgres;

--
-- Name: categorie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competence; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.competence (
    id bigint NOT NULL,
    categorie character varying(255),
    description text,
    libelle character varying(255),
    niveaux_raw text
);


ALTER TABLE public.competence OWNER TO postgres;

--
-- Name: competence_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.competence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conge; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conge (
    id bigint NOT NULL,
    date_debut character varying(255),
    date_fin character varying(255),
    nb_jours integer,
    statut character varying(255),
    employee_id bigint,
    type_absence_conge_id bigint
);


ALTER TABLE public.conge OWNER TO postgres;

--
-- Name: conge_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contrat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contrat (
    id bigint NOT NULL,
    date_debut character varying(255),
    date_fin character varying(255),
    statut character varying(255),
    employee_id bigint,
    service_id bigint,
    type_contrat_id bigint
);


ALTER TABLE public.contrat OWNER TO postgres;

--
-- Name: contrat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contrat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contrat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    directeur_id bigint
);


ALTER TABLE public.department OWNER TO postgres;

--
-- Name: department_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.department_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.department_seq OWNER TO postgres;

--
-- Name: direction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.direction (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255),
    department_id bigint
);


ALTER TABLE public.direction OWNER TO postgres;

--
-- Name: direction_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.direction_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.direction_seq OWNER TO postgres;

--
-- Name: echelon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.echelon (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255)
);


ALTER TABLE public.echelon OWNER TO postgres;

--
-- Name: echelon_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.echelon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.echelon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emploi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emploi (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255)
);


ALTER TABLE public.emploi OWNER TO postgres;

--
-- Name: emploi_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.emploi_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.emploi_seq OWNER TO postgres;

--
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    id bigint NOT NULL,
    email character varying(255),
    extra_data text,
    matricule character varying(255),
    name character varying(255),
    nom character varying(255),
    phone character varying(255),
    prenom character varying(255),
    state character varying(255),
    telephone character varying(255),
    department_id bigint,
    direction_id bigint,
    emploi_id bigint,
    fonction_id bigint,
    service_id bigint,
    superviseur_id bigint,
    categorie_id bigint,
    echelon_id bigint,
    grade_id bigint,
    grille_salariale_id bigint,
    CONSTRAINT employee_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIF'::character varying, 'INACTIF'::character varying, 'SUSPENDU'::character varying, 'EN_CONGE'::character varying])::text[])))
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_entretien; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluation_entretien (
    id bigint NOT NULL,
    commentaires text,
    date character varying(255),
    employee_id bigint,
    employee_name character varying(255),
    evaluateur character varying(255),
    note integer,
    objectifs text
);


ALTER TABLE public.evaluation_entretien OWNER TO postgres;

--
-- Name: evaluation_entretien_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluation_entretien ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_entretien_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exoneration_fiscale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exoneration_fiscale (
    id bigint NOT NULL,
    actif boolean,
    base_calcul character varying(255),
    code character varying(255),
    libelle character varying(255),
    montant_plafond double precision,
    nb_charges_famille integer,
    taux_exoneration double precision,
    type_exoneration character varying(255)
);


ALTER TABLE public.exoneration_fiscale OWNER TO postgres;

--
-- Name: exoneration_fiscale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exoneration_fiscale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exoneration_fiscale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fonction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fonction (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255),
    type_nomination character varying(255)
);


ALTER TABLE public.fonction OWNER TO postgres;

--
-- Name: fonction_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fonction_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fonction_seq OWNER TO postgres;

--
-- Name: formation_catalogue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formation_catalogue (
    id bigint NOT NULL,
    description text,
    duree integer,
    titre character varying(255)
);


ALTER TABLE public.formation_catalogue OWNER TO postgres;

--
-- Name: formation_catalogue_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formation_catalogue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formation_catalogue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: formation_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formation_session (
    id bigint NOT NULL,
    date character varying(255),
    description text,
    duree integer,
    participants integer,
    statut character varying(255),
    titre character varying(255)
);


ALTER TABLE public.formation_session OWNER TO postgres;

--
-- Name: formation_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formation_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formation_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: generic_ref_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.generic_ref_data (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    categorie character varying(255),
    code character varying(255),
    description text,
    grade character varying(255),
    libelle character varying(255),
    taux double precision,
    type character varying(255),
    type_retenue character varying(255)
);


ALTER TABLE public.generic_ref_data OWNER TO postgres;

--
-- Name: generic_ref_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.generic_ref_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generic_ref_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grade; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grade (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255)
);


ALTER TABLE public.grade OWNER TO postgres;

--
-- Name: grade_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.grade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grille_salariale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grille_salariale (
    id bigint NOT NULL,
    salaire_base numeric(10,2),
    category character varying(255),
    classe character varying(255),
    echelle character varying(255),
    echellon character varying(255),
    categorie_id bigint,
    echelon_id bigint,
    grade_id bigint
);


ALTER TABLE public.grille_salariale OWNER TO postgres;

--
-- Name: grille_salariale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.grille_salariale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grille_salariale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mobilite_demande; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mobilite_demande (
    id bigint NOT NULL,
    commentaires text,
    date_demande character varying(255),
    employee_id bigint,
    employee_name character varying(255),
    poste_cible character varying(255),
    service_cible character varying(255),
    statut character varying(255),
    type_mobility character varying(255)
);


ALTER TABLE public.mobilite_demande OWNER TO postgres;

--
-- Name: mobilite_demande_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mobilite_demande ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mobilite_demande_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mode_paiement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mode_paiement (
    id bigint NOT NULL,
    actif boolean,
    banque_nom character varying(255),
    code character varying(255),
    description character varying(255),
    exigerib boolean,
    libelle character varying(255)
);


ALTER TABLE public.mode_paiement OWNER TO postgres;

--
-- Name: mode_paiement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mode_paiement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mode_paiement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: param_groupe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.param_groupe (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255),
    categorie_id bigint,
    grade_id bigint,
    categorie_text character varying(255),
    grade_text character varying(255)
);


ALTER TABLE public.param_groupe OWNER TO postgres;

--
-- Name: param_groupe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.param_groupe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.param_groupe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: param_prise_en_charge; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.param_prise_en_charge (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255),
    taux double precision
);


ALTER TABLE public.param_prise_en_charge OWNER TO postgres;

--
-- Name: param_prise_en_charge_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.param_prise_en_charge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.param_prise_en_charge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: param_retraite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.param_retraite (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255),
    taux double precision,
    grade_id bigint
);


ALTER TABLE public.param_retraite OWNER TO postgres;

--
-- Name: param_retraite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.param_retraite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.param_retraite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parametrage_indemnite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parametrage_indemnite (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    plafond_exoneration double precision,
    regle_type character varying(255),
    taux double precision,
    taux_exoneration double precision,
    type_nomination character varying(255),
    categorie_id bigint,
    fonction_id bigint,
    grade_id bigint,
    type_indemnite_id bigint,
    categorie_str character varying(255),
    fonction_str character varying(255),
    grade_str character varying(255),
    type_indemnite character varying(255)
);


ALTER TABLE public.parametrage_indemnite OWNER TO postgres;

--
-- Name: parametrage_indemnite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parametrage_indemnite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parametrage_indemnite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parametre_rh; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parametre_rh (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    code character varying(255),
    description character varying(255),
    libelle character varying(255),
    type character varying(255)
);


ALTER TABLE public.parametre_rh OWNER TO postgres;

--
-- Name: parametre_rh_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parametre_rh ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parametre_rh_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prise_en_charge_famille; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prise_en_charge_famille (
    id bigint NOT NULL,
    actif boolean,
    date_naissance date,
    lien_parente character varying(255),
    nom_membre character varying(255),
    plafond_annuel double precision,
    prenom_membre character varying(255),
    statut_matrimonial character varying(255),
    taux_prise_en_charge double precision,
    employee_id bigint
);


ALTER TABLE public.prise_en_charge_famille OWNER TO postgres;

--
-- Name: prise_en_charge_famille_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prise_en_charge_famille ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prise_en_charge_famille_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retenue_salariale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.retenue_salariale (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255),
    libelle character varying(255),
    mensualite double precision,
    montant_total double precision,
    resteapayer double precision,
    taux double precision,
    employee_id bigint,
    type_retenue_employe_id bigint
);


ALTER TABLE public.retenue_salariale OWNER TO postgres;

--
-- Name: retenue_salariale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.retenue_salariale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retenue_salariale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rubrique_paie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rubrique_paie (
    id bigint NOT NULL,
    actif boolean,
    code_rubrique character varying(255),
    cotisable boolean,
    formule_calcul character varying(255),
    imposable boolean,
    libelle character varying(255),
    type_rubrique character varying(255)
);


ALTER TABLE public.rubrique_paie OWNER TO postgres;

--
-- Name: rubrique_paie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rubrique_paie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rubrique_paie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255),
    department_id bigint,
    direction_id bigint
);


ALTER TABLE public.service OWNER TO postgres;

--
-- Name: service_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.service_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.service_seq OWNER TO postgres;

--
-- Name: type_absence_conge; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_absence_conge (
    id bigint NOT NULL,
    code character varying(255),
    name character varying(255)
);


ALTER TABLE public.type_absence_conge OWNER TO postgres;

--
-- Name: type_absence_conge_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.type_absence_conge_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.type_absence_conge_seq OWNER TO postgres;

--
-- Name: type_contrat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_contrat (
    id bigint NOT NULL,
    code character varying(255),
    name character varying(255)
);


ALTER TABLE public.type_contrat OWNER TO postgres;

--
-- Name: type_contrat_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.type_contrat_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.type_contrat_seq OWNER TO postgres;

--
-- Name: type_indemnite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_indemnite (
    id bigint NOT NULL,
    code character varying(255),
    description character varying(255),
    name character varying(255),
    plafond_exoneration double precision,
    taux_exoneration double precision
);


ALTER TABLE public.type_indemnite OWNER TO postgres;

--
-- Name: type_indemnite_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.type_indemnite_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.type_indemnite_seq OWNER TO postgres;

--
-- Name: type_retenue_emploi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_retenue_emploi (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255),
    taux double precision,
    type_retenue_employe_id bigint
);


ALTER TABLE public.type_retenue_emploi OWNER TO postgres;

--
-- Name: type_retenue_emploi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type_retenue_emploi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_retenue_emploi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_retenue_employe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_retenue_employe (
    id bigint NOT NULL,
    actif boolean,
    code character varying(255) NOT NULL,
    description text,
    libelle character varying(255)
);


ALTER TABLE public.type_retenue_employe OWNER TO postgres;

--
-- Name: type_retenue_employe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type_retenue_employe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_retenue_employe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    email character varying(255),
    nom character varying(255),
    password character varying(255),
    prenom character varying(255),
    role character varying(255),
    username character varying(255)
);


ALTER TABLE public.utilisateur OWNER TO postgres;

--
-- Name: utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: absence; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.absence (id, date, duree, motif, statut, employee_id, type_absence_conge_id) FROM stdin;
\.


--
-- Data for Name: agence; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.agence (id, actif, adresse, code_agence, email, nom_agence, telephone, ville) FROM stdin;
\.


--
-- Data for Name: bareme_iuts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bareme_iuts (id, abattement_forfaitaire, actif, code_tranche, taux_imposition, tranche_max, tranche_min) FROM stdin;
\.


--
-- Data for Name: categorie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categorie (id, actif, code, description, libelle, taux_abattement) FROM stdin;
1	t	1	Groupe I — Agent d'exécution (Base 95 945 FCFA)	1ÈRE CATEGORIE	\N
2	t	2	Groupe I — Agent d'exécution (Base 104 474 FCFA)	2ÈME CATEGORIE	\N
3	t	3	Groupe I — Agent d'exécution (Base 107 135 FCFA)	3ÈME CATEGORIE	\N
4	t	4	Groupe I — Employé qualifié (Base 115 558 FCFA)	4ÈME CATEGORIE	\N
5	t	5	Groupe I — Employé qualifié (Base 128 831 FCFA)	5ÈME CATEGORIE	\N
6	t	6	Groupe I — Employé principal (Base 157 940 FCFA)	6ÈME CATEGORIE	\N
7	t	7	Groupe I — Agent de maîtrise (Base 176 441 FCFA)	7ÈME CATEGORIE	\N
8	t	I	Groupe II — Agent de maîtrise / Technicien (Base 173 090 FCFA)	CLASSE I	\N
9	t	II	Groupe II — Agent de maîtrise supérieur (Base 203 834 FCFA)	CLASSE II	\N
10	t	III	Groupe II — Cadre moyen (Base 278 697 FCFA)	CLASSE III	\N
11	t	IV	Groupe II — Cadre supérieur (Base 405 758 FCFA)	CLASSE IV	\N
12	t	V	Groupe III — Cadre de direction (Base 581 390 FCFA)	CLASSE V	\N
13	t	VI	Groupe III — Chef de Département (Base 599 438 FCFA)	CLASSE VI	\N
14	t	VII	Groupe III — Directeur (Base 631 454 FCFA)	CLASSE VII	\N
15	t	VIII	Groupe III — Directeur Général / Exécutif (Base 710 386 FCFA)	CLASSE VIII	\N
16	t	CL4	\N	CL4	\N
\.


--
-- Data for Name: competence; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.competence (id, categorie, description, libelle, niveaux_raw) FROM stdin;
\.


--
-- Data for Name: conge; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.conge (id, date_debut, date_fin, nb_jours, statut, employee_id, type_absence_conge_id) FROM stdin;
\.


--
-- Data for Name: contrat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contrat (id, date_debut, date_fin, statut, employee_id, service_id, type_contrat_id) FROM stdin;
\.


--
-- Data for Name: department; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.department (id, code, name, directeur_id) FROM stdin;
\.


--
-- Data for Name: direction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.direction (id, code, description, name, department_id) FROM stdin;
1	DIR-001	Pilotage stratégique et gouvernance BPBF	Direction Générale (DG)	\N
2	DIR-002	Exploitation bancaire et gestion du réseau d'agences	Direction des Opérations Bancaires (DOB)	\N
3	DIR-003	Systèmes d'information, réseaux bancaires & Cash Point	Direction Monétique & SI (DMSI)	\N
4	DIR-004	Gestion du personnel, paie et développement des compétences	Direction des Ressources Humaines (DRH)	\N
5	DIR-005	Gestion financière, comptabilité et trésorerie bancaire	Direction Financière & Trésorerie (DFT)	\N
\.


--
-- Data for Name: echelon; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.echelon (id, actif, code, description, libelle) FROM stdin;
1	t	1	Niveau d'ancienneté 1 (Progression d'échelon)	Échelon 1
2	t	2	Niveau d'ancienneté 2 (Progression d'échelon)	Échelon 2
3	t	3	Niveau d'ancienneté 3 (Progression d'échelon)	Échelon 3
4	t	4	Niveau d'ancienneté 4 (Progression d'échelon)	Échelon 4
5	t	5	Niveau d'ancienneté 5 (Progression d'échelon)	Échelon 5
6	t	6	Niveau d'ancienneté 6 (Progression d'échelon)	Échelon 6
7	t	7	Niveau d'ancienneté 7 (Progression d'échelon)	Échelon 7
8	t	8	Niveau d'ancienneté 8 (Progression d'échelon)	Échelon 8
9	t	9	Niveau d'ancienneté 9 (Progression d'échelon)	Échelon 9
10	t	10	Niveau d'ancienneté 10 (Progression d'échelon)	Échelon 10
11	t	11	Niveau d'ancienneté 11 (Progression d'échelon)	Échelon 11
12	t	12	Niveau d'ancienneté 12 (Progression d'échelon)	Échelon 12
13	t	13	Niveau d'ancienneté 13 (Progression d'échelon)	Échelon 13
14	t	14	Niveau d'ancienneté 14 (Progression d'échelon)	Échelon 14
15	t	15	Niveau d'ancienneté 15 (Progression d'échelon)	Échelon 15
16	t	E06	\N	E06
\.


--
-- Data for Name: emploi; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.emploi (id, code, name) FROM stdin;
1	EMP-001	Directeur Général
2	EMP-002	Directeur de Département
3	EMP-003	Chef de Service
4	EMP-004	Analyste Financier / Comptable
5	EMP-005	Ingénieur Monétique / SI
6	EMP-006	Caissier Principal
7	EMP-007	Gestionnaire Cash Point
8	EMP-008	Chargé de Clientèle Entreprises & PME
9	EMP-009	Auditeur Interne & Contrôleur de Gestion
\.


--
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (id, email, extra_data, matricule, name, nom, phone, prenom, state, telephone, department_id, direction_id, emploi_id, fonction_id, service_id, superviseur_id, categorie_id, echelon_id, grade_id, grille_salariale_id) FROM stdin;
6	b.compaore@bpbf.bf	{"categorie":"CL4","echelon":"E06","grade":"CL4E06","salaireBase":470385.0,"primeLogement":120000.0,"primeTransport":75000.0,"primeResponsabilite":30000.0,"fonction":"Chauffeur","poste":"Agent Bancaire","service":"Service Opérations","direction":"Direction Générale (DG)","departement":"Direction Générale","dateEmbauche":"2020-01-01","statut":"Actif","modePaiement":"Virement bancaire","banque":"Banque Postale du Burkina Faso (BPBF)","iban":"BF01 01001 000000000000 00","intituleCompte":"Boukari COMPAORE","categoriePro":"CL4"}	EMP-006	COMPAORE Boukari	COMPAORE	+226 60 12 34 56	Boukari	ACTIF	+226 60 12 34 56	\N	\N	\N	103	\N	\N	16	16	\N	381
5	a.traore@bpbf.bf	{"categorie":"C1","echelon":"E01","grade":"C1E01","salaireBase":95945.0,"primeLogement":150000.0,"primeTransport":75000.0,"primeResponsabilite":100000.0,"fonction":"Responsable de Département","poste":"Agent Bancaire","service":"Service Opérations","direction":"Direction Générale (DG)","departement":"Direction Générale","dateEmbauche":"2020-01-01","statut":"Actif","modePaiement":"Virement bancaire","banque":"Banque Postale du Burkina Faso (BPBF)","iban":"BF01 01001 000000000000 00","intituleCompte":"Aminata TRAORE","categoriePro":"C1"}	EMP-005	TRAORE Aminata	TRAORE	+226 75 44 33 22	Aminata	ACTIF	+226 75 44 33 22	\N	\N	\N	3	\N	\N	\N	\N	\N	226
4	y.kabore@bpbf.bf	{"categorie":"CL4","echelon":"E04","grade":"CL4E04","salaireBase":443383.0,"primeLogement":45000.0,"primeTransport":45000.0,"primeResponsabilite":0.0,"categoriePro":"CL4"}	EMP-004	KABORE Yacouba	KABORE	+226 71 22 33 44	Yacouba	ACTIF	+226 71 22 33 44	\N	\N	\N	\N	\N	\N	16	\N	\N	379
3	m.ouedraogo@bpbf.bf	{"categorie":"CL6","echelon":"E03","grade":"CL6E03","salaireBase":599438,"primeLogement":150000,"primeTransport":75000,"primeResponsabilite":100000}	EMP-003	Mariam OUEDRAOGO	OUEDRAOGO	+226 78 99 88 77	Mariam	ACTIF	+226 78 99 88 77	\N	\N	\N	\N	\N	\N	\N	\N	\N	408
7	f.sanogo@bpbf.bf	{"categorie":"CL1","echelon":"E01","grade":"CL1E01","salaireBase":173090.0,"primeLogement":35000,"primeTransport":30000,"primeResponsabilite":30000,"fonction":"Agent simple","poste":"Agent Bancaire","service":"Service Opérations","direction":"Direction Générale (DG)","departement":"Direction Générale","dateEmbauche":"2020-01-01","statut":"Actif","salaireBrut":473090.0,"modePaiement":"Virement bancaire","banque":"Banque Postale du Burkina Faso (BPBF)","iban":"BF01 01001 000000000000 00","intituleCompte":"Fatoumata SANOGO","categoriePro":"CL1"}	EMP-007	SANOGO Fatoumata	SANOGO	+226 72 34 56 78	Fatoumata	ACTIF	+226 72 34 56 78	\N	\N	\N	\N	\N	\N	\N	\N	\N	331
8	b.yerbanga@bpbf.bf	{"categorie":"C4","echelon":"E01","grade":"C4E01","salaireBase":150000,"primeLogement":100000,"primeTransport":75000,"primeResponsabilite":75000,"enfants":[{"prenom":"Junior","nom":"Yerbanga","dateNaissance":"2016-05-12","scolarise":true}]}	EMP-008	Blaise YERBANGA	YERBANGA	+226 70 99 88 11	Blaise	ACTIF	+226 70 99 88 11	\N	\N	\N	\N	\N	\N	\N	\N	\N	271
9	david.zorom@bpbf.bf	{"categorie":"C4","echelon":"E01","grade":"C4E01","salaireBase":115558,"primeLogement":25000,"primeTransport":25000,"primeResponsabilite":20000}	EMP-009	David ZOROM	ZOROM	+226 70 00 11 22	David	ACTIF	+226 70 00 11 22	\N	\N	\N	\N	\N	\N	\N	\N	\N	271
10	davidff@bpbf.bf	{"categorie":"C1","echelon":"E01","grade":"C1E01","salaireBase":95945,"primeLogement":25000,"primeTransport":25000,"primeResponsabilite":0}	EMP-010	Davidff ZOROFFFF	ZOROFFFF	+226 70 11 22 44	Davidff	ACTIF	+226 70 11 22 44	\N	\N	\N	\N	\N	\N	\N	\N	\N	226
11	444@bpbf.bf	{"categorie":"C1","echelon":"E01","grade":"C1E01","salaireBase":95945,"primeLogement":25000,"primeTransport":25000,"primeResponsabilite":0}	EMP-011	4 444	444	+226 70 11 22 55	4	ACTIF	+226 70 11 22 55	\N	\N	\N	\N	\N	\N	\N	\N	\N	226
12	ff@bpbf.bf	{"categorie":"C1","echelon":"E01","grade":"C1E01","salaireBase":95945,"primeLogement":25000,"primeTransport":25000,"primeResponsabilite":0}	EMP-012	F F	F	+226 70 11 22 66	F	ACTIF	+226 70 11 22 66	\N	\N	\N	\N	\N	\N	\N	\N	\N	226
13	ali.sanou@bpbf.bf	{"categorie":"C1","echelon":"E01","grade":"C1E01","salaireBase":95945,"primeLogement":25000,"primeTransport":25000,"primeResponsabilite":0}	EMP-013	Ali SANOU	SANOU	+226 70 11 22 77	Ali	ACTIF	+226 70 11 22 77	\N	\N	\N	\N	\N	\N	\N	\N	\N	226
14	hh@bpbf.bf	{"categorie":"C1","echelon":"E01","grade":"C1E01","salaireBase":95945,"primeLogement":25000,"primeTransport":25000,"primeResponsabilite":0}	EMP-014	H H	H	+226 70 11 22 88	H	ACTIF	+226 70 11 22 88	\N	\N	\N	\N	\N	\N	\N	\N	\N	226
1	a.sawadogo@bpbf.bf	{"categorie":"C1","echelon":"E03","grade":"C1E03","salaireBase":116093.0,"primeLogement":35000.0,"primeTransport":30000.0,"primeResponsabilite":0.0,"fonction":"Agent simple","poste":"Agent Bancaire","service":"Service Opérations","direction":"Direction Générale (DG)","departement":"Direction Générale","dateEmbauche":"2020-01-01","statut":"Actif","categoriePro":"C1","salaireBrut":266093.0,"modePaiement":"Virement bancaire","banque":"Banque Postale du Burkina Faso (BPBF)","iban":"BF01 01001 000000000000 00","intituleCompte":"Abdoulaye SAWADOGO"}	EMP-001	SAWADOGO Abdoulaye	SAWADOGO	+226 70 11 22 33	Abdoulaye	ACTIF	+226 70 11 22 33	\N	\N	\N	\N	\N	\N	\N	\N	\N	228
2	d.zorom@bpbf.bf	{"categorie":"C1","echelon":"E01","grade":"C1E01","salaireBase":95945.0,"primeLogement":200000,"primeTransport":100000,"primeResponsabilite":150000,"fonction":"Agent simple","poste":"Agent Bancaire","service":"Service Opérations","direction":"Direction Générale (DG)","departement":"Direction Générale","dateEmbauche":"2020-01-01","statut":"Actif","salaireBrut":245945.0,"modePaiement":"Virement bancaire","banque":"Banque Postale du Burkina Faso (BPBF)","iban":"BF01 01001 000000000000 00","intituleCompte":"David Pascal ZOROM","categoriePro":"C1"}	EMP-002	ZOROM David Pascal	ZOROM	+226 76 55 44 33	David Pascal	ACTIF	+226 76 55 44 33	\N	\N	\N	\N	\N	\N	\N	\N	\N	226
\.


--
-- Data for Name: evaluation_entretien; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluation_entretien (id, commentaires, date, employee_id, employee_name, evaluateur, note, objectifs) FROM stdin;
\.


--
-- Data for Name: exoneration_fiscale; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exoneration_fiscale (id, actif, base_calcul, code, libelle, montant_plafond, nb_charges_famille, taux_exoneration, type_exoneration) FROM stdin;
\.


--
-- Data for Name: fonction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fonction (id, actif, code, description, name, type_nomination) FROM stdin;
1	t	FCT-001		Directeur Général (DG)	NOMMEE
2	t	FCT-002		Directeur de Département	NOMMEE
3	t	FCT-003		Responsable de Département	NOMMEE
4	t	FCT-004		Chef de Service	NOMMEE
5	t	FCT-005	\N	Responsable d'Unité	NON_NOMMEE
6	t	FCT-006	\N	Chef d'Agence Bancaire	NOMMEE
7	t	FCT-007	\N	Auditeur Interne Senior	NON_NOMMEE
8	t	FCT-008	\N	Comptable Principal	NON_NOMMEE
9	t	FCT-009	\N	Ingénieur Réseau & SI	NON_NOMMEE
10	t	FCT-010	\N	Analyste Financier Senior	NON_NOMMEE
11	t	FCT-011	\N	Gestionnaire de Portefeuille Clientèle	NON_NOMMEE
12	t	FCT-012	\N	Superviseur Cash Point & Guichet	NON_NOMMEE
13	t	FCT-013	\N	Chargé de Clientèle Particuliers	NON_NOMMEE
14	t	FCT-014		Caissier Principal	NOMMEE
52	t	FCT-1786325359464	\N	Gestionnaire Cash Point	NOMMEE
102	t	FCT-016	\N	Caissier Auxiliaire	NOMMEE
104	t	FCT-018	\N	Assistante de Direction	NOMMEE
105	t	FCT-019	\N	Agent de Liaison	NOMMEE
15	t	FCT-015	\N	Agent d'Accueil & Secrétariat	NON_NOMMEE
103	t	FCT-017		Chauffeur	NOMMEE
\.


--
-- Data for Name: formation_catalogue; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formation_catalogue (id, description, duree, titre) FROM stdin;
\.


--
-- Data for Name: formation_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.formation_session (id, date, description, duree, participants, statut, titre) FROM stdin;
\.


--
-- Data for Name: generic_ref_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.generic_ref_data (id, actif, categorie, code, description, grade, libelle, taux, type, type_retenue) FROM stdin;
1	t	\N	1	Groupe I — Agent d'exécution (Base 95 945 FCFA)	\N	1ÈRE CATEGORIE	\N	categorie	\N
2	t	\N	2	Groupe I — Agent d'exécution (Base 104 474 FCFA)	\N	2ÈME CATEGORIE	\N	categorie	\N
3	t	\N	3	Groupe I — Agent d'exécution (Base 107 135 FCFA)	\N	3ÈME CATEGORIE	\N	categorie	\N
4	t	\N	4	Groupe I — Employé qualifié (Base 115 558 FCFA)	\N	4ÈME CATEGORIE	\N	categorie	\N
5	t	\N	5	Groupe I — Employé qualifié (Base 128 831 FCFA)	\N	5ÈME CATEGORIE	\N	categorie	\N
6	t	\N	6	Groupe I — Employé principal (Base 157 940 FCFA)	\N	6ÈME CATEGORIE	\N	categorie	\N
7	t	\N	7	Groupe I — Agent de maîtrise (Base 176 441 FCFA)	\N	7ÈME CATEGORIE	\N	categorie	\N
8	t	\N	I	Groupe II — Agent de maîtrise / Technicien (Base 173 090 FCFA)	\N	CLASSE I	\N	categorie	\N
9	t	\N	II	Groupe II — Agent de maîtrise supérieur (Base 203 834 FCFA)	\N	CLASSE II	\N	categorie	\N
10	t	\N	III	Groupe II — Cadre moyen (Base 278 697 FCFA)	\N	CLASSE III	\N	categorie	\N
11	t	\N	IV	Groupe II — Cadre supérieur (Base 405 758 FCFA)	\N	CLASSE IV	\N	categorie	\N
12	t	\N	V	Groupe III — Cadre de direction (Base 581 390 FCFA)	\N	CLASSE V	\N	categorie	\N
13	t	\N	VI	Groupe III — Chef de Département (Base 599 438 FCFA)	\N	CLASSE VI	\N	categorie	\N
14	t	\N	VII	Groupe III — Directeur (Base 631 454 FCFA)	\N	CLASSE VII	\N	categorie	\N
15	t	\N	VIII	Groupe III — Directeur Général / Exécutif (Base 710 386 FCFA)	\N	CLASSE VIII	\N	categorie	\N
16	t	\N	GROUPE I	Agents et Employés (Catégories 1 à 7)	\N	GROUPE I	\N	grade	\N
17	t	\N	GROUPE II	Classes I à IV (Agents de Maîtrise et Cadres moyens)	\N	GROUPE II	\N	grade	\N
18	t	\N	GROUPE III	Classes V à VIII (Cadres et Cadres Supérieurs)	\N	GROUPE III	\N	grade	\N
19	t	\N	1	Niveau d'ancienneté 1 (Progression d'échelon)	\N	Échelon 1	\N	echelon	\N
20	t	\N	2	Niveau d'ancienneté 2 (Progression d'échelon)	\N	Échelon 2	\N	echelon	\N
21	t	\N	3	Niveau d'ancienneté 3 (Progression d'échelon)	\N	Échelon 3	\N	echelon	\N
22	t	\N	4	Niveau d'ancienneté 4 (Progression d'échelon)	\N	Échelon 4	\N	echelon	\N
23	t	\N	5	Niveau d'ancienneté 5 (Progression d'échelon)	\N	Échelon 5	\N	echelon	\N
24	t	\N	6	Niveau d'ancienneté 6 (Progression d'échelon)	\N	Échelon 6	\N	echelon	\N
25	t	\N	7	Niveau d'ancienneté 7 (Progression d'échelon)	\N	Échelon 7	\N	echelon	\N
26	t	\N	8	Niveau d'ancienneté 8 (Progression d'échelon)	\N	Échelon 8	\N	echelon	\N
27	t	\N	9	Niveau d'ancienneté 9 (Progression d'échelon)	\N	Échelon 9	\N	echelon	\N
28	t	\N	10	Niveau d'ancienneté 10 (Progression d'échelon)	\N	Échelon 10	\N	echelon	\N
29	t	\N	11	Niveau d'ancienneté 11 (Progression d'échelon)	\N	Échelon 11	\N	echelon	\N
30	t	\N	12	Niveau d'ancienneté 12 (Progression d'échelon)	\N	Échelon 12	\N	echelon	\N
31	t	\N	13	Niveau d'ancienneté 13 (Progression d'échelon)	\N	Échelon 13	\N	echelon	\N
32	t	\N	14	Niveau d'ancienneté 14 (Progression d'échelon)	\N	Échelon 14	\N	echelon	\N
33	t	\N	15	Niveau d'ancienneté 15 (Progression d'échelon)	\N	Échelon 15	\N	echelon	\N
34	t	C1, C2, C3, C4, C5, C6, C7	PG-GROUPE-I	Catégories C1 à C7 rattachées au Groupe I	GROUPE I	GROUPE I	\N	param-groupe	\N
35	t	CL1, CL2, CL3, CL4	PG-GROUPE-II	Classes CL1 à CL4 rattachées au Groupe II	GROUPE II	GROUPE II	\N	param-groupe	\N
36	t	CL5, CL6, CL7, CL8	PG-GROUPE-III	Classes CL5 à CL8 rattachées au Groupe III	GROUPE III	GROUPE III	\N	param-groupe	\N
37	t	CL9, CL10	PG-GROUPE-IV	Classes CL9 à CL10 rattachées au Groupe IV	GROUPE IV	GROUPE IV	\N	param-groupe	\N
38	t	\N	PG-RET-G1	Âge légal de départ à la retraite pour les agents non-cadres (56 ans)	GROUPE I	GROUPE I	56	param-retraite	\N
39	t	\N	PG-RET-G2	GROUPE II : 58 ans	GROUPE II	GROUPE II	58	param-retraite	\N
40	t	\N	PG-RET-G3	GROUPE III : 60 ans	GROUPE III	GROUPE III	60	param-retraite	\N
41	t	\N	PG-RET-G4	GROUPE IV : 63 ans	GROUPE IV	GROUPE IV	63	param-retraite	\N
42	t	\N	PEC-AGE-STD	Âge limite légal pour enfant mineur à charge (strictement inférieur à 18 ans)	\N	Âge Max Enfant Standard	18	param-prise-en-charge	\N
43	t	\N	PEC-AGE-ETUD	Âge limite pour enfant poursuivant des études (strictement inférieur à 20 ans)	\N	Âge Max Enfant Étudiant / Scolarisé	20	param-prise-en-charge	\N
44	t	\N	PEC-CONJOINT	Accorder +1 charge de famille si le conjoint est sans emploi / ne travaille pas	\N	Prise en Charge Conjoint Non-Salarié	1	param-prise-en-charge	\N
45	t	\N	PEC-MAX-CHRG	Plafond maximum de charges fiscales admises pour la réduction IUTS (Burkina Faso)	\N	Nombre de Charges Max Autorisées	4	param-prise-en-charge	\N
46	t	\N	TR-PATRONALE	Part de cotisation patronale prise en charge directement par l'employeur	\N	Part Employeur	\N	type-retenue-employe	\N
47	t	\N	TR-SALARIALE	Part de cotisation salariale prélevée à la source sur la paie de l'agent	\N	Part Agent	\N	type-retenue-employe	\N
48	t	\N	RET-CNSS-SAL	Cotisation sociale obligatoire à la charge de l'employé (5,5% du brut plafonné)	\N	Cotisation Sociale CNSS (Part Agent)	5.5	type-retenue-emploi	Part Agent
49	t	\N	RET-CNSS-PAT	Cotisation patronale obligatoire sécurité sociale (16,0% sur masse salariale)	\N	Cotisation Sociale CNSS (Part Employeur)	16	type-retenue-emploi	Part Employeur
50	t	\N	RET-IUTS	Impôt Unique sur Traitements et Salaires prélevé à la source (Barème progressif)	\N	Impôt IUTS (Impôt sur Salaire)	0	type-retenue-emploi	Retenue Fiscale (IUTS/TPA)
51	t	\N	RET-CRRAE-SAL	Cotisation salariale fonds de pension complémentaire bancaire UMOA	\N	Retraite Complémentaire CRRAE (Part Agent)	3	type-retenue-emploi	Retraite Complémentaire (CRRAE)
52	t	\N	RET-CRRAE-PAT	Contribution patronale retraite complémentaire bancaire UMOA	\N	Retraite Complémentaire CRRAE (Part Pat.)	5	type-retenue-emploi	Part Employeur
53	t	\N	RET-AM-SAL	Part salariale couverture médicale maladie et hospitalisation (25%)	\N	Assurance Maladie Groupe (Part Agent)	2.5	type-retenue-emploi	Assurance Groupe & Santé
54	t	\N	RET-AM-PAT	Prise en charge patronale assurance maladie groupe (75%)	\N	Assurance Maladie Groupe (Part Employeur)	7.5	type-retenue-emploi	Part Employeur
55	t	\N	OUAGA	Capitale politique	\N	Ouagadougou	\N	ville	\N
56	t	\N	OUAHI	Région du Nord	\N	Ouahigouya	\N	ville	\N
59	t	\N	KAYA	Région du Centre-Nord	\N	Kaya	\N	ville	\N
58	t	\N	KOUDOU	Région du Centre-Ouest	\N	Koudougou	\N	ville	\N
61	t	\N	TENKO	Région du Centre-Est	\N	Tenkodogo	\N	ville	\N
62	t	\N	DEDOU	Région de la Boucle du Mouhoun	\N	Dédougou	\N	ville	\N
64	t	\N	MANGA	Région du Centre-Sud	\N	Manga	\N	ville	\N
60	t	\N	BOBO	Capitale économique	\N	Bobo-Dioulasso	\N	ville	\N
57	t	\N	BANF	Région des Cascades	\N	Banfora	\N	ville	\N
63	t	\N	FADA	Région de l'Est	\N	Fada N'gourma	\N	ville	\N
\.


--
-- Data for Name: grade; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grade (id, actif, code, description, libelle) FROM stdin;
1	t	GROUPE I	Agents et Employés (Catégories 1 à 7)	GROUPE I
2	t	GROUPE II	Classes I à IV (Agents de Maîtrise et Cadres moyens)	GROUPE II
3	t	GROUPE III	Classes V à VIII (Cadres et Cadres Supérieurs)	GROUPE III
\.


--
-- Data for Name: grille_salariale; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grille_salariale (id, salaire_base, category, classe, echelle, echellon, categorie_id, echelon_id, grade_id) FROM stdin;
226	95945.00	C1	GROUPE I	Catégorie 1	E01	1	1	1
227	98823.00	C1	GROUPE I	Catégorie 1	E02	1	2	1
228	101788.00	C1	GROUPE I	Catégorie 1	E03	1	3	1
229	104842.00	C1	GROUPE I	Catégorie 1	E04	1	4	1
230	107987.00	C1	GROUPE I	Catégorie 1	E05	1	5	1
231	111227.00	C1	GROUPE I	Catégorie 1	E06	1	6	1
232	114563.00	C1	GROUPE I	Catégorie 1	E07	1	7	1
233	118000.00	C1	GROUPE I	Catégorie 1	E08	1	8	1
234	121540.00	C1	GROUPE I	Catégorie 1	E09	1	9	1
235	125186.00	C1	GROUPE I	Catégorie 1	E10	1	10	1
236	128942.00	C1	GROUPE I	Catégorie 1	E11	1	11	1
237	132810.00	C1	GROUPE I	Catégorie 1	E12	1	12	1
238	136795.00	C1	GROUPE I	Catégorie 1	E13	1	13	1
239	140898.00	C1	GROUPE I	Catégorie 1	E14	1	14	1
240	145125.00	C1	GROUPE I	Catégorie 1	E15	1	15	1
241	104474.00	C2	GROUPE I	Catégorie 2	E01	2	1	1
242	107608.00	C2	GROUPE I	Catégorie 2	E02	2	2	1
243	110836.00	C2	GROUPE I	Catégorie 2	E03	2	3	1
244	114162.00	C2	GROUPE I	Catégorie 2	E04	2	4	1
245	117586.00	C2	GROUPE I	Catégorie 2	E05	2	5	1
246	121114.00	C2	GROUPE I	Catégorie 2	E06	2	6	1
247	124747.00	C2	GROUPE I	Catégorie 2	E07	2	7	1
248	128490.00	C2	GROUPE I	Catégorie 2	E08	2	8	1
249	132345.00	C2	GROUPE I	Catégorie 2	E09	2	9	1
250	136315.00	C2	GROUPE I	Catégorie 2	E10	2	10	1
251	140404.00	C2	GROUPE I	Catégorie 2	E11	2	11	1
252	144616.00	C2	GROUPE I	Catégorie 2	E12	2	12	1
253	148955.00	C2	GROUPE I	Catégorie 2	E13	2	13	1
254	153424.00	C2	GROUPE I	Catégorie 2	E14	2	14	1
255	158026.00	C2	GROUPE I	Catégorie 2	E15	2	15	1
256	107135.00	C3	GROUPE I	Catégorie 3	E01	3	1	1
257	110349.00	C3	GROUPE I	Catégorie 3	E02	3	2	1
258	113660.00	C3	GROUPE I	Catégorie 3	E03	3	3	1
259	117069.00	C3	GROUPE I	Catégorie 3	E04	3	4	1
260	120581.00	C3	GROUPE I	Catégorie 3	E05	3	5	1
261	124199.00	C3	GROUPE I	Catégorie 3	E06	3	6	1
262	127925.00	C3	GROUPE I	Catégorie 3	E07	3	7	1
263	131763.00	C3	GROUPE I	Catégorie 3	E08	3	8	1
264	135715.00	C3	GROUPE I	Catégorie 3	E09	3	9	1
265	139787.00	C3	GROUPE I	Catégorie 3	E10	3	10	1
266	143980.00	C3	GROUPE I	Catégorie 3	E11	3	11	1
267	148300.00	C3	GROUPE I	Catégorie 3	E12	3	12	1
268	152749.00	C3	GROUPE I	Catégorie 3	E13	3	13	1
269	157331.00	C3	GROUPE I	Catégorie 3	E14	3	14	1
270	162051.00	C3	GROUPE I	Catégorie 3	E15	3	15	1
271	115558.00	C4	GROUPE I	Catégorie 4	E01	4	1	1
272	119025.00	C4	GROUPE I	Catégorie 4	E02	4	2	1
273	122595.00	C4	GROUPE I	Catégorie 4	E03	4	3	1
274	126273.00	C4	GROUPE I	Catégorie 4	E04	4	4	1
275	130062.00	C4	GROUPE I	Catégorie 4	E05	4	5	1
276	133963.00	C4	GROUPE I	Catégorie 4	E06	4	6	1
277	137982.00	C4	GROUPE I	Catégorie 4	E07	4	7	1
278	142122.00	C4	GROUPE I	Catégorie 4	E08	4	8	1
279	146385.00	C4	GROUPE I	Catégorie 4	E09	4	9	1
280	150777.00	C4	GROUPE I	Catégorie 4	E10	4	10	1
281	155300.00	C4	GROUPE I	Catégorie 4	E11	4	11	1
282	159959.00	C4	GROUPE I	Catégorie 4	E12	4	12	1
283	164758.00	C4	GROUPE I	Catégorie 4	E13	4	13	1
284	169701.00	C4	GROUPE I	Catégorie 4	E14	4	14	1
285	174792.00	C4	GROUPE I	Catégorie 4	E15	4	15	1
286	128831.00	C5	GROUPE I	Catégorie 5	E01	5	1	1
287	132696.00	C5	GROUPE I	Catégorie 5	E02	5	2	1
288	136677.00	C5	GROUPE I	Catégorie 5	E03	5	3	1
289	140777.00	C5	GROUPE I	Catégorie 5	E04	5	4	1
290	145000.00	C5	GROUPE I	Catégorie 5	E05	5	5	1
291	149350.00	C5	GROUPE I	Catégorie 5	E06	5	6	1
292	153831.00	C5	GROUPE I	Catégorie 5	E07	5	7	1
293	158446.00	C5	GROUPE I	Catégorie 5	E08	5	8	1
294	163199.00	C5	GROUPE I	Catégorie 5	E09	5	9	1
295	168095.00	C5	GROUPE I	Catégorie 5	E10	5	10	1
296	173138.00	C5	GROUPE I	Catégorie 5	E11	5	11	1
297	178332.00	C5	GROUPE I	Catégorie 5	E12	5	12	1
298	183682.00	C5	GROUPE I	Catégorie 5	E13	5	13	1
299	189193.00	C5	GROUPE I	Catégorie 5	E14	5	14	1
300	194868.00	C5	GROUPE I	Catégorie 5	E15	5	15	1
301	157940.00	C6	GROUPE I	Catégorie 6	E01	6	1	1
302	162678.00	C6	GROUPE I	Catégorie 6	E02	6	2	1
303	167559.00	C6	GROUPE I	Catégorie 6	E03	6	3	1
304	172585.00	C6	GROUPE I	Catégorie 6	E04	6	4	1
305	177763.00	C6	GROUPE I	Catégorie 6	E05	6	5	1
306	183096.00	C6	GROUPE I	Catégorie 6	E06	6	6	1
307	188589.00	C6	GROUPE I	Catégorie 6	E07	6	7	1
308	194246.00	C6	GROUPE I	Catégorie 6	E08	6	8	1
309	200074.00	C6	GROUPE I	Catégorie 6	E09	6	9	1
310	206076.00	C6	GROUPE I	Catégorie 6	E10	6	10	1
311	212258.00	C6	GROUPE I	Catégorie 6	E11	6	11	1
312	218626.00	C6	GROUPE I	Catégorie 6	E12	6	12	1
313	225185.00	C6	GROUPE I	Catégorie 6	E13	6	13	1
314	231940.00	C6	GROUPE I	Catégorie 6	E14	6	14	1
315	238898.00	C6	GROUPE I	Catégorie 6	E15	6	15	1
316	176441.00	C7	GROUPE I	Catégorie 7	E01	7	1	1
317	181734.00	C7	GROUPE I	Catégorie 7	E02	7	2	1
318	187186.00	C7	GROUPE I	Catégorie 7	E03	7	3	1
319	192802.00	C7	GROUPE I	Catégorie 7	E04	7	4	1
320	198586.00	C7	GROUPE I	Catégorie 7	E05	7	5	1
321	204543.00	C7	GROUPE I	Catégorie 7	E06	7	6	1
322	210680.00	C7	GROUPE I	Catégorie 7	E07	7	7	1
323	217000.00	C7	GROUPE I	Catégorie 7	E08	7	8	1
324	223510.00	C7	GROUPE I	Catégorie 7	E09	7	9	1
325	230215.00	C7	GROUPE I	Catégorie 7	E10	7	10	1
326	237122.00	C7	GROUPE I	Catégorie 7	E11	7	11	1
327	244236.00	C7	GROUPE I	Catégorie 7	E12	7	12	1
328	251563.00	C7	GROUPE I	Catégorie 7	E13	7	13	1
329	259110.00	C7	GROUPE I	Catégorie 7	E14	7	14	1
330	266883.00	C7	GROUPE I	Catégorie 7	E15	7	15	1
331	173090.00	CL1	GROUPE II	Classe I	E01	8	1	2
332	178283.00	CL1	GROUPE II	Classe I	E02	8	2	2
333	183631.00	CL1	GROUPE II	Classe I	E03	8	3	2
334	189140.00	CL1	GROUPE II	Classe I	E04	8	4	2
335	194814.00	CL1	GROUPE II	Classe I	E05	8	5	2
336	200659.00	CL1	GROUPE II	Classe I	E06	8	6	2
337	206679.00	CL1	GROUPE II	Classe I	E07	8	7	2
338	212879.00	CL1	GROUPE II	Classe I	E08	8	8	2
339	219265.00	CL1	GROUPE II	Classe I	E09	8	9	2
340	225843.00	CL1	GROUPE II	Classe I	E10	8	10	2
341	232618.00	CL1	GROUPE II	Classe I	E11	8	11	2
342	239597.00	CL1	GROUPE II	Classe I	E12	8	12	2
343	246785.00	CL1	GROUPE II	Classe I	E13	8	13	2
344	254189.00	CL1	GROUPE II	Classe I	E14	8	14	2
345	261814.00	CL1	GROUPE II	Classe I	E15	8	15	2
346	203834.00	CL2	GROUPE II	Classe II	E01	9	1	2
347	209949.00	CL2	GROUPE II	Classe II	E02	9	2	2
348	216247.00	CL2	GROUPE II	Classe II	E03	9	3	2
349	222735.00	CL2	GROUPE II	Classe II	E04	9	4	2
350	229417.00	CL2	GROUPE II	Classe II	E05	9	5	2
351	236299.00	CL2	GROUPE II	Classe II	E06	9	6	2
352	243388.00	CL2	GROUPE II	Classe II	E07	9	7	2
353	250690.00	CL2	GROUPE II	Classe II	E08	9	8	2
354	258211.00	CL2	GROUPE II	Classe II	E09	9	9	2
355	265957.00	CL2	GROUPE II	Classe II	E10	9	10	2
356	273936.00	CL2	GROUPE II	Classe II	E11	9	11	2
357	282154.00	CL2	GROUPE II	Classe II	E12	9	12	2
358	290619.00	CL2	GROUPE II	Classe II	E13	9	13	2
359	299337.00	CL2	GROUPE II	Classe II	E14	9	14	2
360	308317.00	CL2	GROUPE II	Classe II	E15	9	15	2
361	278697.00	CL3	GROUPE II	Classe III	E01	10	1	2
362	287058.00	CL3	GROUPE II	Classe III	E02	10	2	2
363	295670.00	CL3	GROUPE II	Classe III	E03	10	3	2
364	304540.00	CL3	GROUPE II	Classe III	E04	10	4	2
365	313676.00	CL3	GROUPE II	Classe III	E05	10	5	2
366	323086.00	CL3	GROUPE II	Classe III	E06	10	6	2
367	332779.00	CL3	GROUPE II	Classe III	E07	10	7	2
368	342762.00	CL3	GROUPE II	Classe III	E08	10	8	2
369	353045.00	CL3	GROUPE II	Classe III	E09	10	9	2
370	363636.00	CL3	GROUPE II	Classe III	E10	10	10	2
371	374545.00	CL3	GROUPE II	Classe III	E11	10	11	2
372	385782.00	CL3	GROUPE II	Classe III	E12	10	12	2
373	397355.00	CL3	GROUPE II	Classe III	E13	10	13	2
374	409276.00	CL3	GROUPE II	Classe III	E14	10	14	2
375	421554.00	CL3	GROUPE II	Classe III	E15	10	15	2
376	405758.00	CL4	GROUPE II	Classe IV	E01	11	1	2
377	417931.00	CL4	GROUPE II	Classe IV	E02	11	2	2
378	430469.00	CL4	GROUPE II	Classe IV	E03	11	3	2
379	443383.00	CL4	GROUPE II	Classe IV	E04	11	4	2
380	456684.00	CL4	GROUPE II	Classe IV	E05	11	5	2
381	470385.00	CL4	GROUPE II	Classe IV	E06	11	6	2
382	484496.00	CL4	GROUPE II	Classe IV	E07	11	7	2
383	499031.00	CL4	GROUPE II	Classe IV	E08	11	8	2
384	514002.00	CL4	GROUPE II	Classe IV	E09	11	9	2
385	529422.00	CL4	GROUPE II	Classe IV	E10	11	10	2
386	545305.00	CL4	GROUPE II	Classe IV	E11	11	11	2
387	561664.00	CL4	GROUPE II	Classe IV	E12	11	12	2
388	578514.00	CL4	GROUPE II	Classe IV	E13	11	13	2
389	595869.00	CL4	GROUPE II	Classe IV	E14	11	14	2
390	613745.00	CL4	GROUPE II	Classe IV	E15	11	15	2
391	581390.00	CL5	GROUPE III	Classe V	E01	12	1	3
392	598832.00	CL5	GROUPE III	Classe V	E02	12	2	3
393	616797.00	CL5	GROUPE III	Classe V	E03	12	3	3
394	635301.00	CL5	GROUPE III	Classe V	E04	12	4	3
395	654360.00	CL5	GROUPE III	Classe V	E05	12	5	3
396	673990.00	CL5	GROUPE III	Classe V	E06	12	6	3
397	694210.00	CL5	GROUPE III	Classe V	E07	12	7	3
398	715036.00	CL5	GROUPE III	Classe V	E08	12	8	3
399	736487.00	CL5	GROUPE III	Classe V	E09	12	9	3
400	758582.00	CL5	GROUPE III	Classe V	E10	12	10	3
401	781340.00	CL5	GROUPE III	Classe V	E11	12	11	3
402	804780.00	CL5	GROUPE III	Classe V	E12	12	12	3
403	828923.00	CL5	GROUPE III	Classe V	E13	12	13	3
404	853791.00	CL5	GROUPE III	Classe V	E14	12	14	3
405	879405.00	CL5	GROUPE III	Classe V	E15	12	15	3
406	599438.00	CL6	GROUPE III	Classe VI	E01	13	1	3
407	617421.00	CL6	GROUPE III	Classe VI	E02	13	2	3
408	635944.00	CL6	GROUPE III	Classe VI	E03	13	3	3
409	655022.00	CL6	GROUPE III	Classe VI	E04	13	4	3
410	674673.00	CL6	GROUPE III	Classe VI	E05	13	5	3
411	694913.00	CL6	GROUPE III	Classe VI	E06	13	6	3
412	715760.00	CL6	GROUPE III	Classe VI	E07	13	7	3
413	737233.00	CL6	GROUPE III	Classe VI	E08	13	8	3
414	759350.00	CL6	GROUPE III	Classe VI	E09	13	9	3
415	782131.00	CL6	GROUPE III	Classe VI	E10	13	10	3
416	805595.00	CL6	GROUPE III	Classe VI	E11	13	11	3
417	829762.00	CL6	GROUPE III	Classe VI	E12	13	12	3
418	854655.00	CL6	GROUPE III	Classe VI	E13	13	13	3
419	880295.00	CL6	GROUPE III	Classe VI	E14	13	14	3
420	906704.00	CL6	GROUPE III	Classe VI	E15	13	15	3
421	631454.00	CL7	GROUPE III	Classe VII	E01	14	1	3
422	650398.00	CL7	GROUPE III	Classe VII	E02	14	2	3
423	669910.00	CL7	GROUPE III	Classe VII	E03	14	3	3
424	690007.00	CL7	GROUPE III	Classe VII	E04	14	4	3
425	710707.00	CL7	GROUPE III	Classe VII	E05	14	5	3
426	732028.00	CL7	GROUPE III	Classe VII	E06	14	6	3
427	753989.00	CL7	GROUPE III	Classe VII	E07	14	7	3
428	776609.00	CL7	GROUPE III	Classe VII	E08	14	8	3
429	799907.00	CL7	GROUPE III	Classe VII	E09	14	9	3
430	823904.00	CL7	GROUPE III	Classe VII	E10	14	10	3
431	848621.00	CL7	GROUPE III	Classe VII	E11	14	11	3
432	874080.00	CL7	GROUPE III	Classe VII	E12	14	12	3
433	900302.00	CL7	GROUPE III	Classe VII	E13	14	13	3
434	927311.00	CL7	GROUPE III	Classe VII	E14	14	14	3
435	955131.00	CL7	GROUPE III	Classe VII	E15	14	15	3
436	710386.00	CL8	GROUPE III	Classe VIII	E01	15	1	3
437	731698.00	CL8	GROUPE III	Classe VIII	E02	15	2	3
438	753649.00	CL8	GROUPE III	Classe VIII	E03	15	3	3
439	776258.00	CL8	GROUPE III	Classe VIII	E04	15	4	3
440	799546.00	CL8	GROUPE III	Classe VIII	E05	15	5	3
441	823532.00	CL8	GROUPE III	Classe VIII	E06	15	6	3
442	848238.00	CL8	GROUPE III	Classe VIII	E07	15	7	3
443	873685.00	CL8	GROUPE III	Classe VIII	E08	15	8	3
444	899896.00	CL8	GROUPE III	Classe VIII	E09	15	9	3
445	926893.00	CL8	GROUPE III	Classe VIII	E10	15	10	3
446	954699.00	CL8	GROUPE III	Classe VIII	E11	15	11	3
447	983340.00	CL8	GROUPE III	Classe VIII	E12	15	12	3
448	1012841.00	CL8	GROUPE III	Classe VIII	E13	15	13	3
449	1043226.00	CL8	GROUPE III	Classe VIII	E14	15	14	3
450	1074523.00	CL8	GROUPE III	Classe VIII	E15	15	15	3
\.


--
-- Data for Name: mobilite_demande; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mobilite_demande (id, commentaires, date_demande, employee_id, employee_name, poste_cible, service_cible, statut, type_mobility) FROM stdin;
\.


--
-- Data for Name: mode_paiement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mode_paiement (id, actif, banque_nom, code, description, exigerib, libelle) FROM stdin;
\.


--
-- Data for Name: param_groupe; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.param_groupe (id, actif, code, description, libelle, categorie_id, grade_id, categorie_text, grade_text) FROM stdin;
1	t	PG-GROUPE-I	Catégories C1 à C7 rattachées au Groupe I	GROUPE I	\N	\N	C1, C2, C3, C4, C5, C6, C7	GROUPE I
2	t	PG-GROUPE-II	Classes CL1 à CL4 rattachées au Groupe II	GROUPE II	\N	\N	CL1, CL2, CL3, CL4	GROUPE II
3	t	PG-GROUPE-III	Classes CL5 à CL8 rattachées au Groupe III	GROUPE III	\N	\N	CL5, CL6, CL7, CL8	GROUPE III
4	t	PG-GROUPE-IV	Classes CL9 à CL10 rattachées au Groupe IV	GROUPE IV	\N	\N	CL9, CL10	GROUPE IV
\.


--
-- Data for Name: param_prise_en_charge; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.param_prise_en_charge (id, actif, code, description, libelle, taux) FROM stdin;
1	t	PEC-AGE-STD	Âge limite légal pour enfant mineur à charge (strictement inférieur à 18 ans)	Âge Max Enfant Standard	18
2	t	PEC-AGE-ETUD	Âge limite pour enfant poursuivant des études (strictement inférieur à 20 ans)	Âge Max Enfant Étudiant / Scolarisé	20
3	t	PEC-CONJOINT	Accorder +1 charge de famille si le conjoint est sans emploi / ne travaille pas	Prise en Charge Conjoint Non-Salarié	1
4	t	PEC-MAX-CHRG	Plafond maximum de charges fiscales admises pour la réduction IUTS (Burkina Faso)	Nombre de Charges Max Autorisées	4
\.


--
-- Data for Name: param_retraite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.param_retraite (id, actif, code, description, libelle, taux, grade_id) FROM stdin;
1	t	PG-RET-G1	Âge légal de départ à la retraite pour les agents non-cadres (56 ans)	GROUPE I	56	\N
2	t	PG-RET-G2	GROUPE II : 58 ans	GROUPE II	58	\N
3	t	PG-RET-G3	GROUPE III : 60 ans	GROUPE III	60	\N
4	t	PG-RET-G4	GROUPE IV : 63 ans	GROUPE IV	63	\N
\.


--
-- Data for Name: parametrage_indemnite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parametrage_indemnite (id, actif, code, plafond_exoneration, regle_type, taux, taux_exoneration, type_nomination, categorie_id, fonction_id, grade_id, type_indemnite_id, categorie_str, fonction_str, grade_str, type_indemnite) FROM stdin;
1486	t	IND-FCT-103-1	\N	NOMINATION	15000	\N	NOMMEE	\N	103	\N	\N	\N	Chauffeur	\N	Prime d'astreinte
1473	t	PI-NOM-CS-CMP	0	NOMINATION	75000	0	NOMMEE	\N	4	\N	\N		CHEF DE SERVICE		Indemnité compensatrice
1474	t	PI-NOM-CA-FCT	0	NOMINATION	75000	0	NOMMEE	\N	6	\N	\N		CHEF D'AGENCE		Indemnité de fonction
1475	t	PI-NOM-CA-TRP	75000	NOMINATION	75000	100	NOMMEE	\N	6	\N	2		CHEF D'AGENCE		Indemnité de Transport
1476	t	PI-NOM-CA-LOG	0	NOMINATION	100000	0	NOMMEE	\N	6	\N	1		CHEF D'AGENCE		Indemnité de Logement
1477	t	PI-NOM-CA-CMP	0	NOMINATION	75000	0	NOMMEE	\N	6	\N	\N		CHEF D'AGENCE		Indemnité compensatrice
1478	t	PI-SPEC-CP-CS	0	SPECIFIQUE	40000	0	NOMMEE	\N	14	\N	4		CAISSIER PRINCIPAL		Indemnité de caisse
1479	t	PI-SPEC-GCP-CP	0	SPECIFIQUE	50000	0	NOMMEE	\N	12	\N	4		GESTIONNAIRE CASH POINT		Indemnité Cash Point
1480	t	PI-SPEC-GCP-CS	0	SPECIFIQUE	25000	0	NOMMEE	\N	12	\N	4		GESTIONNAIRE CASH POINT		Indemnité de caisse
1481	t	PI-SPEC-CA-CS	0	SPECIFIQUE	25000	0	NOMMEE	\N	102	\N	4		CAISSIER AUXILIAIRE		Indemnité de caisse
1482	t	PI-SPEC-CHF-AST	0	SPECIFIQUE	15000	0	NOMMEE	\N	103	\N	4		CHAUFFEUR		Prime d'astreinte
1483	t	PI-SPEC-AD-AST	0	SPECIFIQUE	30000	0	NOMMEE	\N	104	\N	4		ASSISTANTE DE DIRECTION		Prime d'astreinte
1484	t	PI-SPEC-AL-AST	0	SPECIFIQUE	15000	0	NOMMEE	\N	105	\N	4		AGENT DE LIAISON		Prime d'astreinte
1436	t	PI-G1-LOG	0	ORDINAIRE	35000	0	NON_NOMMEE	\N	\N	1	1	C1, C2, C3, C4, C5, C6, C7		GROUPE I	Indemnité de Logement
1437	t	PI-G1-TRP	30000	ORDINAIRE	30000	100	NON_NOMMEE	\N	\N	1	2	C1, C2, C3, C4, C5, C6, C7		GROUPE I	Indemnité de Transport
1438	t	PI-G2-CL1-LOG	0	ORDINAIRE	45000	0	NON_NOMMEE	\N	\N	2	1	CL1		GROUPE II	Indemnité de Logement
1439	t	PI-G2-CL1-TRP	45000	ORDINAIRE	45000	100	NON_NOMMEE	\N	\N	2	2	CL1		GROUPE II	Indemnité de Transport
1440	t	PI-G2-CL1-SUJ	0	ORDINAIRE	20000	0	NON_NOMMEE	\N	\N	2	4	CL1		GROUPE II	Indemnité de Sujétion
1441	t	PI-G2-CL2-LOG	0	ORDINAIRE	45000	0	NON_NOMMEE	\N	\N	2	1	CL2		GROUPE II	Indemnité de Logement
1442	t	PI-G2-CL2-TRP	45000	ORDINAIRE	45000	100	NON_NOMMEE	\N	\N	2	2	CL2		GROUPE II	Indemnité de Transport
1443	t	PI-G2-CL2-SUJ	0	ORDINAIRE	30000	0	NON_NOMMEE	\N	\N	2	4	CL2		GROUPE II	Indemnité de Sujétion
1444	t	PI-G2-CL3-LOG	0	ORDINAIRE	50000	0	NON_NOMMEE	\N	\N	2	1	CL3		GROUPE II	Indemnité de Logement
1445	t	PI-G2-CL3-TRP	50000	ORDINAIRE	50000	100	NON_NOMMEE	\N	\N	2	2	CL3		GROUPE II	Indemnité de Transport
1446	t	PI-G2-CL3-SUJ	0	ORDINAIRE	40000	0	NON_NOMMEE	\N	\N	2	4	CL3		GROUPE II	Indemnité de Sujétion
1447	t	PI-G2-CL4-LOG	0	ORDINAIRE	60000	0	NON_NOMMEE	16	\N	2	1	CL4		GROUPE II	Indemnité de Logement
1448	t	PI-G2-CL4-TRP	50000	ORDINAIRE	50000	100	NON_NOMMEE	16	\N	2	2	CL4		GROUPE II	Indemnité de Transport
1449	t	PI-G2-CL4-SUJ	0	ORDINAIRE	50000	0	NON_NOMMEE	16	\N	2	4	CL4		GROUPE II	Indemnité de Sujétion
1450	t	PI-G3-CL5-LOG	0	ORDINAIRE	90000	0	NON_NOMMEE	\N	\N	3	1	CL5		GROUPE III	Indemnité de Logement
1451	t	PI-G3-CL5-TRP	60000	ORDINAIRE	60000	100	NON_NOMMEE	\N	\N	3	2	CL5		GROUPE III	Indemnité de Transport
1452	t	PI-G3-CL5-SUJ	0	ORDINAIRE	60000	0	NON_NOMMEE	\N	\N	3	4	CL5		GROUPE III	Indemnité de Sujétion
1453	t	PI-G3-CL6-LOG	0	ORDINAIRE	100000	0	NON_NOMMEE	\N	\N	3	1	CL6		GROUPE III	Indemnité de Logement
1454	t	PI-G3-CL6-TRP	75000	ORDINAIRE	75000	100	NON_NOMMEE	\N	\N	3	2	CL6		GROUPE III	Indemnité de Transport
1455	t	PI-G3-CL6-SUJ	0	ORDINAIRE	60000	0	NON_NOMMEE	\N	\N	3	4	CL6		GROUPE III	Indemnité de Sujétion
1456	t	PI-G3-CL7-LOG	0	ORDINAIRE	110000	0	NON_NOMMEE	\N	\N	3	1	CL7		GROUPE III	Indemnité de Logement
1457	t	PI-G3-CL7-TRP	80000	ORDINAIRE	80000	100	NON_NOMMEE	\N	\N	3	2	CL7		GROUPE III	Indemnité de Transport
1458	t	PI-G3-CL7-SUJ	0	ORDINAIRE	70000	0	NON_NOMMEE	\N	\N	3	4	CL7		GROUPE III	Indemnité de Sujétion
1459	t	PI-G3-CL8-LOG	0	ORDINAIRE	150000	0	NON_NOMMEE	\N	\N	3	1	CL8		GROUPE III	Indemnité de Logement
1460	t	PI-G3-CL8-TRP	100000	ORDINAIRE	100000	100	NON_NOMMEE	\N	\N	3	2	CL8		GROUPE III	Indemnité de Transport
1461	t	PI-G3-CL8-SUJ	0	ORDINAIRE	80000	0	NON_NOMMEE	\N	\N	3	4	CL8		GROUPE III	Indemnité de Sujétion
1462	t	PI-NOM-DIR-FCT	0	NOMINATION	150000	0	NOMMEE	\N	2	\N	\N		DIRECTEUR DE DÉPARTEMENT		Indemnité de fonction
1463	t	PI-NOM-DIR-TRP	100000	NOMINATION	100000	100	NOMMEE	\N	2	\N	2		DIRECTEUR DE DÉPARTEMENT		Indemnité de Transport
1464	t	PI-NOM-DIR-LOG	0	NOMINATION	200000	0	NOMMEE	\N	2	\N	1		DIRECTEUR DE DÉPARTEMENT		Indemnité de Logement
1465	t	PI-NOM-DIR-CMP	0	NOMINATION	100000	0	NOMMEE	\N	2	\N	\N		DIRECTEUR DE DÉPARTEMENT		Indemnité compensatrice
1466	t	PI-NOM-RESP-FCT	0	NOMINATION	100000	0	NOMMEE	\N	3	\N	\N		RESPONSABLE DE DÉPARTEMENT		Indemnité de fonction
1467	t	PI-NOM-RESP-TRP	75000	NOMINATION	75000	100	NOMMEE	\N	3	\N	2		RESPONSABLE DE DÉPARTEMENT		Indemnité de Transport
1468	t	PI-NOM-RESP-LOG	0	NOMINATION	150000	0	NOMMEE	\N	3	\N	1		RESPONSABLE DE DÉPARTEMENT		Indemnité de Logement
1469	t	PI-NOM-RESP-CMP	0	NOMINATION	75000	0	NOMMEE	\N	3	\N	\N		RESPONSABLE DE DÉPARTEMENT		Indemnité compensatrice
1470	t	PI-NOM-CS-FCT	0	NOMINATION	80000	0	NOMMEE	\N	4	\N	\N		CHEF DE SERVICE		Indemnité de fonction
1471	t	PI-NOM-CS-TRP	75000	NOMINATION	75000	100	NOMMEE	\N	4	\N	2		CHEF DE SERVICE		Indemnité de Transport
1472	t	PI-NOM-CS-LOG	0	NOMINATION	120000	0	NOMMEE	\N	4	\N	1		CHEF DE SERVICE		Indemnité de Logement
\.


--
-- Data for Name: parametre_rh; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parametre_rh (id, actif, code, description, libelle, type) FROM stdin;
\.


--
-- Data for Name: prise_en_charge_famille; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prise_en_charge_famille (id, actif, date_naissance, lien_parente, nom_membre, plafond_annuel, prenom_membre, statut_matrimonial, taux_prise_en_charge, employee_id) FROM stdin;
\.


--
-- Data for Name: retenue_salariale; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.retenue_salariale (id, actif, code, libelle, mensualite, montant_total, resteapayer, taux, employee_id, type_retenue_employe_id) FROM stdin;
\.


--
-- Data for Name: rubrique_paie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rubrique_paie (id, actif, code_rubrique, cotisable, formule_calcul, imposable, libelle, type_rubrique) FROM stdin;
\.


--
-- Data for Name: service; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service (id, code, description, name, department_id, direction_id) FROM stdin;
1	SRV-001	Gestion des cartes, GAB, TPE et services Cash Point	Service Monétique & Cash Point	\N	\N
2	SRV-002	Administration du personnel et calcul de la paie	Service Gestion du Personnel & Paie	\N	\N
3	SRV-003	Comptabilité générale bancaire et gestion de la caisse	Service Comptabilité & Trésorerie	\N	\N
4	SRV-004	Gestion des opérations de caisse et transferts	Service Opérations de Guichet	\N	\N
5	SRV-005	Analyse et octroi des prêts aux particuliers et pro	Service Crédit & Engagements	\N	\N
\.


--
-- Data for Name: type_absence_conge; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_absence_conge (id, code, name) FROM stdin;
\.


--
-- Data for Name: type_contrat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_contrat (id, code, name) FROM stdin;
\.


--
-- Data for Name: type_indemnite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_indemnite (id, code, description, name, plafond_exoneration, taux_exoneration) FROM stdin;
1	IND-LOG	Indemnité liée au logement du personnel	Indemnité de Logement	0	0
2	IND-TRP	Indemnité forfaitaire de déplacement	Indemnité de Transport	30000	100
3	IND-RSP	Prime de responsabilité de fonction	Indemnité de Responsabilité	0	0
4	IND-SUT	Indemnité pour risque de caisse et manipulation de fonds	Indemnité de Sujétion & Caisse	50000	100
5	IND-RIS	Indemnité spécifique risques métier banque	Indemnité de Risque Bancaire	0	0
\.


--
-- Data for Name: type_retenue_emploi; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_retenue_emploi (id, actif, code, description, libelle, taux, type_retenue_employe_id) FROM stdin;
1	t	RET-CNSS-SAL	Cotisation sociale obligatoire à la charge de l'employé (5,5% du brut plafonné)	Cotisation Sociale CNSS (Part Agent)	5.5	\N
2	t	RET-CNSS-PAT	Cotisation patronale obligatoire sécurité sociale (16,0% sur masse salariale)	Cotisation Sociale CNSS (Part Employeur)	16	\N
3	t	RET-IUTS	Impôt Unique sur Traitements et Salaires prélevé à la source (Barème progressif)	Impôt IUTS (Impôt sur Salaire)	0	\N
4	t	RET-CRRAE-SAL	Cotisation salariale fonds de pension complémentaire bancaire UMOA	Retraite Complémentaire CRRAE (Part Agent)	3	\N
5	t	RET-CRRAE-PAT	Contribution patronale retraite complémentaire bancaire UMOA	Retraite Complémentaire CRRAE (Part Pat.)	5	\N
6	t	RET-AM-SAL	Part salariale couverture médicale maladie et hospitalisation (25%)	Assurance Maladie Groupe (Part Agent)	2.5	\N
7	t	RET-AM-PAT	Prise en charge patronale assurance maladie groupe (75%)	Assurance Maladie Groupe (Part Employeur)	7.5	\N
\.


--
-- Data for Name: type_retenue_employe; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_retenue_employe (id, actif, code, description, libelle) FROM stdin;
1	t	TR-PATRONALE	Part de cotisation patronale prise en charge directement par l'employeur	Part Employeur
2	t	TR-SALARIALE	Part de cotisation salariale prélevée à la source sur la paie de l'agent	Part Agent
\.


--
-- Data for Name: utilisateur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.utilisateur (id, actif, email, nom, password, prenom, role, username) FROM stdin;
1	t	davidzorom9@gmail.com	ZOROM	5621	David	ADMIN	davidzorom
2	t	marie.dupont@societe.com	DUPONT	password123	Marie	USER	marie.dupont
\.


--
-- Name: absence_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.absence_id_seq', 1, false);


--
-- Name: agence_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.agence_id_seq', 1, false);


--
-- Name: bareme_iuts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bareme_iuts_id_seq', 1, false);


--
-- Name: categorie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorie_id_seq', 16, true);


--
-- Name: competence_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.competence_id_seq', 1, false);


--
-- Name: conge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.conge_id_seq', 1, false);


--
-- Name: contrat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contrat_id_seq', 1, false);


--
-- Name: department_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.department_seq', 1, false);


--
-- Name: direction_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.direction_seq', 51, true);


--
-- Name: echelon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.echelon_id_seq', 16, true);


--
-- Name: emploi_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.emploi_seq', 51, true);


--
-- Name: employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_id_seq', 14, true);


--
-- Name: evaluation_entretien_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluation_entretien_id_seq', 1, false);


--
-- Name: exoneration_fiscale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exoneration_fiscale_id_seq', 1, false);


--
-- Name: fonction_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fonction_seq', 151, true);


--
-- Name: formation_catalogue_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formation_catalogue_id_seq', 1, false);


--
-- Name: formation_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formation_session_id_seq', 1, false);


--
-- Name: generic_ref_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.generic_ref_data_id_seq', 64, true);


--
-- Name: grade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grade_id_seq', 3, true);


--
-- Name: grille_salariale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grille_salariale_id_seq', 450, true);


--
-- Name: mobilite_demande_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mobilite_demande_id_seq', 1, false);


--
-- Name: mode_paiement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mode_paiement_id_seq', 1, false);


--
-- Name: param_groupe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.param_groupe_id_seq', 4, true);


--
-- Name: param_prise_en_charge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.param_prise_en_charge_id_seq', 4, true);


--
-- Name: param_retraite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.param_retraite_id_seq', 4, true);


--
-- Name: parametrage_indemnite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parametrage_indemnite_id_seq', 1486, true);


--
-- Name: parametre_rh_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parametre_rh_id_seq', 1, false);


--
-- Name: prise_en_charge_famille_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prise_en_charge_famille_id_seq', 1, false);


--
-- Name: retenue_salariale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.retenue_salariale_id_seq', 1, false);


--
-- Name: rubrique_paie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rubrique_paie_id_seq', 1, false);


--
-- Name: service_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_seq', 51, true);


--
-- Name: type_absence_conge_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_absence_conge_seq', 1, false);


--
-- Name: type_contrat_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_contrat_seq', 1, false);


--
-- Name: type_indemnite_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_indemnite_seq', 51, true);


--
-- Name: type_retenue_emploi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_retenue_emploi_id_seq', 7, true);


--
-- Name: type_retenue_employe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_retenue_employe_id_seq', 2, true);


--
-- Name: utilisateur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utilisateur_id_seq', 2, true);


--
-- Name: absence absence_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absence
    ADD CONSTRAINT absence_pkey PRIMARY KEY (id);


--
-- Name: agence agence_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agence
    ADD CONSTRAINT agence_pkey PRIMARY KEY (id);


--
-- Name: bareme_iuts bareme_iuts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bareme_iuts
    ADD CONSTRAINT bareme_iuts_pkey PRIMARY KEY (id);


--
-- Name: categorie categorie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorie
    ADD CONSTRAINT categorie_pkey PRIMARY KEY (id);


--
-- Name: competence competence_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.competence
    ADD CONSTRAINT competence_pkey PRIMARY KEY (id);


--
-- Name: conge conge_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conge
    ADD CONSTRAINT conge_pkey PRIMARY KEY (id);


--
-- Name: contrat contrat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrat
    ADD CONSTRAINT contrat_pkey PRIMARY KEY (id);


--
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- Name: direction direction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direction
    ADD CONSTRAINT direction_pkey PRIMARY KEY (id);


--
-- Name: echelon echelon_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echelon
    ADD CONSTRAINT echelon_pkey PRIMARY KEY (id);


--
-- Name: emploi emploi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emploi
    ADD CONSTRAINT emploi_pkey PRIMARY KEY (id);


--
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- Name: evaluation_entretien evaluation_entretien_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_entretien
    ADD CONSTRAINT evaluation_entretien_pkey PRIMARY KEY (id);


--
-- Name: exoneration_fiscale exoneration_fiscale_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exoneration_fiscale
    ADD CONSTRAINT exoneration_fiscale_pkey PRIMARY KEY (id);


--
-- Name: fonction fonction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fonction
    ADD CONSTRAINT fonction_pkey PRIMARY KEY (id);


--
-- Name: formation_catalogue formation_catalogue_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formation_catalogue
    ADD CONSTRAINT formation_catalogue_pkey PRIMARY KEY (id);


--
-- Name: formation_session formation_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formation_session
    ADD CONSTRAINT formation_session_pkey PRIMARY KEY (id);


--
-- Name: generic_ref_data generic_ref_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.generic_ref_data
    ADD CONSTRAINT generic_ref_data_pkey PRIMARY KEY (id);


--
-- Name: grade grade_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade
    ADD CONSTRAINT grade_pkey PRIMARY KEY (id);


--
-- Name: grille_salariale grille_salariale_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grille_salariale
    ADD CONSTRAINT grille_salariale_pkey PRIMARY KEY (id);


--
-- Name: mobilite_demande mobilite_demande_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobilite_demande
    ADD CONSTRAINT mobilite_demande_pkey PRIMARY KEY (id);


--
-- Name: mode_paiement mode_paiement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mode_paiement
    ADD CONSTRAINT mode_paiement_pkey PRIMARY KEY (id);


--
-- Name: param_groupe param_groupe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_groupe
    ADD CONSTRAINT param_groupe_pkey PRIMARY KEY (id);


--
-- Name: param_prise_en_charge param_prise_en_charge_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_prise_en_charge
    ADD CONSTRAINT param_prise_en_charge_pkey PRIMARY KEY (id);


--
-- Name: param_retraite param_retraite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_retraite
    ADD CONSTRAINT param_retraite_pkey PRIMARY KEY (id);


--
-- Name: parametrage_indemnite parametrage_indemnite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametrage_indemnite
    ADD CONSTRAINT parametrage_indemnite_pkey PRIMARY KEY (id);


--
-- Name: parametre_rh parametre_rh_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametre_rh
    ADD CONSTRAINT parametre_rh_pkey PRIMARY KEY (id);


--
-- Name: prise_en_charge_famille prise_en_charge_famille_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prise_en_charge_famille
    ADD CONSTRAINT prise_en_charge_famille_pkey PRIMARY KEY (id);


--
-- Name: retenue_salariale retenue_salariale_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retenue_salariale
    ADD CONSTRAINT retenue_salariale_pkey PRIMARY KEY (id);


--
-- Name: rubrique_paie rubrique_paie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rubrique_paie
    ADD CONSTRAINT rubrique_paie_pkey PRIMARY KEY (id);


--
-- Name: service service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT service_pkey PRIMARY KEY (id);


--
-- Name: type_absence_conge type_absence_conge_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_absence_conge
    ADD CONSTRAINT type_absence_conge_pkey PRIMARY KEY (id);


--
-- Name: type_contrat type_contrat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_contrat
    ADD CONSTRAINT type_contrat_pkey PRIMARY KEY (id);


--
-- Name: type_indemnite type_indemnite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_indemnite
    ADD CONSTRAINT type_indemnite_pkey PRIMARY KEY (id);


--
-- Name: type_retenue_emploi type_retenue_emploi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_retenue_emploi
    ADD CONSTRAINT type_retenue_emploi_pkey PRIMARY KEY (id);


--
-- Name: type_retenue_employe type_retenue_employe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_retenue_employe
    ADD CONSTRAINT type_retenue_employe_pkey PRIMARY KEY (id);


--
-- Name: type_retenue_employe uk1eh649goyuhfb2g6ipcq0svgs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_retenue_employe
    ADD CONSTRAINT uk1eh649goyuhfb2g6ipcq0svgs UNIQUE (code);


--
-- Name: param_groupe uk5qbliblhb7nircp8teowirkwv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_groupe
    ADD CONSTRAINT uk5qbliblhb7nircp8teowirkwv UNIQUE (code);


--
-- Name: param_retraite uk5utp062t4x0s3sj3iadu6gj4j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_retraite
    ADD CONSTRAINT uk5utp062t4x0s3sj3iadu6gj4j UNIQUE (code);


--
-- Name: categorie uk61bt8i9mmldlno8ctl94y5rgv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorie
    ADD CONSTRAINT uk61bt8i9mmldlno8ctl94y5rgv UNIQUE (code);


--
-- Name: echelon uk7qcey1bp6lefgkkmmn5j61w5j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.echelon
    ADD CONSTRAINT uk7qcey1bp6lefgkkmmn5j61w5j UNIQUE (code);


--
-- Name: fonction ukhkw3j8ggepcpnqr9bys830loe; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fonction
    ADD CONSTRAINT ukhkw3j8ggepcpnqr9bys830loe UNIQUE (code);


--
-- Name: service ukjxqx9q5tehvt65cvnfydu83uw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT ukjxqx9q5tehvt65cvnfydu83uw UNIQUE (code);


--
-- Name: direction ukkkhsl5cq3pss844mcebj0v0pe; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direction
    ADD CONSTRAINT ukkkhsl5cq3pss844mcebj0v0pe UNIQUE (code);


--
-- Name: emploi uklqgkebjoe1xudngr51e4kseau; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emploi
    ADD CONSTRAINT uklqgkebjoe1xudngr51e4kseau UNIQUE (code);


--
-- Name: grade ukmfpeq9u7tfkalk2vbwwibtf4f; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade
    ADD CONSTRAINT ukmfpeq9u7tfkalk2vbwwibtf4f UNIQUE (code);


--
-- Name: type_retenue_emploi ukn0rqyef4van6244r54saa5y64; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_retenue_emploi
    ADD CONSTRAINT ukn0rqyef4van6244r54saa5y64 UNIQUE (code);


--
-- Name: param_prise_en_charge ukonx03gl50om2pok43114n6v0n; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_prise_en_charge
    ADD CONSTRAINT ukonx03gl50om2pok43114n6v0n UNIQUE (code);


--
-- Name: department ukq8ymhgj6pt1msox0o3bg51uvo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT ukq8ymhgj6pt1msox0o3bg51uvo UNIQUE (code);


--
-- Name: parametrage_indemnite ukqfsorb4y5c21e45roqo3txs54; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametrage_indemnite
    ADD CONSTRAINT ukqfsorb4y5c21e45roqo3txs54 UNIQUE (code);


--
-- Name: utilisateur utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT utilisateur_pkey PRIMARY KEY (id);


--
-- Name: param_groupe fk1mdvfw2xpqma0m5q4p28gvsux; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_groupe
    ADD CONSTRAINT fk1mdvfw2xpqma0m5q4p28gvsux FOREIGN KEY (categorie_id) REFERENCES public.categorie(id);


--
-- Name: parametrage_indemnite fk22c1o4eafbf9kxb4avfywhujn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametrage_indemnite
    ADD CONSTRAINT fk22c1o4eafbf9kxb4avfywhujn FOREIGN KEY (grade_id) REFERENCES public.grade(id);


--
-- Name: department fk2np9wto506j1m3420yopknpl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk2np9wto506j1m3420yopknpl FOREIGN KEY (directeur_id) REFERENCES public.employee(id);


--
-- Name: service fk2wikcukwmad7oaks9539e8450; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT fk2wikcukwmad7oaks9539e8450 FOREIGN KEY (direction_id) REFERENCES public.direction(id);


--
-- Name: contrat fk3w5bgcyqwaaaly3ax5011id4g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrat
    ADD CONSTRAINT fk3w5bgcyqwaaaly3ax5011id4g FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: employee fk46e2sks77ihxgibbwh7c13pay; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fk46e2sks77ihxgibbwh7c13pay FOREIGN KEY (fonction_id) REFERENCES public.fonction(id);


--
-- Name: absence fk47guo9k0vpfqxa3engckwwkuv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absence
    ADD CONSTRAINT fk47guo9k0vpfqxa3engckwwkuv FOREIGN KEY (type_absence_conge_id) REFERENCES public.type_absence_conge(id);


--
-- Name: retenue_salariale fk5oc0cdd3alx57fpqet7r0f7tg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retenue_salariale
    ADD CONSTRAINT fk5oc0cdd3alx57fpqet7r0f7tg FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: conge fk6pbu1dyagwn7g38dci9abx8ew; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conge
    ADD CONSTRAINT fk6pbu1dyagwn7g38dci9abx8ew FOREIGN KEY (type_absence_conge_id) REFERENCES public.type_absence_conge(id);


--
-- Name: contrat fk7dol63w3s57avky5yqol0kns8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrat
    ADD CONSTRAINT fk7dol63w3s57avky5yqol0kns8 FOREIGN KEY (type_contrat_id) REFERENCES public.type_contrat(id);


--
-- Name: employee fk7fyj7yqc3iywse41oe6ubggge; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fk7fyj7yqc3iywse41oe6ubggge FOREIGN KEY (superviseur_id) REFERENCES public.employee(id);


--
-- Name: prise_en_charge_famille fkacira2nfuv6odpqxeh1gjr3rs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prise_en_charge_famille
    ADD CONSTRAINT fkacira2nfuv6odpqxeh1gjr3rs FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: employee fkbejtwvg9bxus2mffsm3swj3u9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fkbejtwvg9bxus2mffsm3swj3u9 FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: grille_salariale fkd1yy1fyl3c24mx9ydd7uj03bl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grille_salariale
    ADD CONSTRAINT fkd1yy1fyl3c24mx9ydd7uj03bl FOREIGN KEY (echelon_id) REFERENCES public.echelon(id);


--
-- Name: type_retenue_emploi fkd27nbwl6borayv981909iiuup; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_retenue_emploi
    ADD CONSTRAINT fkd27nbwl6borayv981909iiuup FOREIGN KEY (type_retenue_employe_id) REFERENCES public.type_retenue_employe(id);


--
-- Name: parametrage_indemnite fkegskqwrnc4vo558e2s47ixab9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametrage_indemnite
    ADD CONSTRAINT fkegskqwrnc4vo558e2s47ixab9 FOREIGN KEY (type_indemnite_id) REFERENCES public.type_indemnite(id);


--
-- Name: employee fketxqlsukxp334c4mte0yp47bp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fketxqlsukxp334c4mte0yp47bp FOREIGN KEY (direction_id) REFERENCES public.direction(id);


--
-- Name: employee fkeun6noo0ifjdsdeukk3j44d4n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fkeun6noo0ifjdsdeukk3j44d4n FOREIGN KEY (categorie_id) REFERENCES public.categorie(id);


--
-- Name: parametrage_indemnite fkgxr0of58428uya0gl555yl4ex; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametrage_indemnite
    ADD CONSTRAINT fkgxr0of58428uya0gl555yl4ex FOREIGN KEY (fonction_id) REFERENCES public.fonction(id);


--
-- Name: contrat fkiw3y1y9t02lnm0y2ehe8joumn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrat
    ADD CONSTRAINT fkiw3y1y9t02lnm0y2ehe8joumn FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: grille_salariale fkjdbesw4vk7dn1j1fobmwuci96; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grille_salariale
    ADD CONSTRAINT fkjdbesw4vk7dn1j1fobmwuci96 FOREIGN KEY (categorie_id) REFERENCES public.categorie(id);


--
-- Name: param_retraite fkk8sbuh7qtdlnnenitrt25b93e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_retraite
    ADD CONSTRAINT fkk8sbuh7qtdlnnenitrt25b93e FOREIGN KEY (grade_id) REFERENCES public.grade(id);


--
-- Name: direction fklrts62iwm8orihklfxe3n8gxq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direction
    ADD CONSTRAINT fklrts62iwm8orihklfxe3n8gxq FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: employee fkn6mje2tx88laybhlg806pox0o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fkn6mje2tx88laybhlg806pox0o FOREIGN KEY (grade_id) REFERENCES public.grade(id);


--
-- Name: employee fknfb9ji42j0a78tr0mqi9fyd77; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fknfb9ji42j0a78tr0mqi9fyd77 FOREIGN KEY (emploi_id) REFERENCES public.emploi(id);


--
-- Name: employee fknfnksddiw9h5j5vrr04s211xy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fknfnksddiw9h5j5vrr04s211xy FOREIGN KEY (grille_salariale_id) REFERENCES public.grille_salariale(id);


--
-- Name: employee fknyjr2bfcr1y0tl1uoiuqf5v4p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fknyjr2bfcr1y0tl1uoiuqf5v4p FOREIGN KEY (echelon_id) REFERENCES public.echelon(id);


--
-- Name: employee fkpeiwfkfseogttspgvybly8cp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fkpeiwfkfseogttspgvybly8cp FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: parametrage_indemnite fkqwgfv5mpnsjbjt2fd5p5elygf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametrage_indemnite
    ADD CONSTRAINT fkqwgfv5mpnsjbjt2fd5p5elygf FOREIGN KEY (categorie_id) REFERENCES public.categorie(id);


--
-- Name: conge fkr9mlgnjx2myhjy36perwhivt6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conge
    ADD CONSTRAINT fkr9mlgnjx2myhjy36perwhivt6 FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: service fkraufppqo77l38jmsyefkcdcnn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT fkraufppqo77l38jmsyefkcdcnn FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: grille_salariale fkrawfllm924roo9apoa3wk8fhj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grille_salariale
    ADD CONSTRAINT fkrawfllm924roo9apoa3wk8fhj FOREIGN KEY (grade_id) REFERENCES public.grade(id);


--
-- Name: param_groupe fks2m4auvfcoqvds6jig83fq8vv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.param_groupe
    ADD CONSTRAINT fks2m4auvfcoqvds6jig83fq8vv FOREIGN KEY (grade_id) REFERENCES public.grade(id);


--
-- Name: absence fks69fc883x11wl5lkx9vjhf5ym; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.absence
    ADD CONSTRAINT fks69fc883x11wl5lkx9vjhf5ym FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: retenue_salariale fksu9twahewc3t3gnnc0kb175rs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retenue_salariale
    ADD CONSTRAINT fksu9twahewc3t3gnnc0kb175rs FOREIGN KEY (type_retenue_employe_id) REFERENCES public.type_retenue_employe(id);


--
-- PostgreSQL database dump complete
--

\unrestrict XS1eEWavleW8dDepOUfdD5sbwRRKCAduzsG0baCIXXWxklj2vF8svsL0JBZHWR1

