spring.application.name=sirh_backend

# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:sigrh_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:sigrh_user}
spring.datasource.password=${DB_PASSWORD:sigrh_password_123}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=false

# ===============================
# TOMCAT & MULTIPART
# ===============================
server.tomcat.max-http-form-post-size=52428800
server.tomcat.max-swallow-size=52428800
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=8081
server.address=0.0.0.0
