spring.application.name=sirh_backend

# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sigrh_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=60000

# ===============================
# JPA / HIBERNATE & DATA SEEDING
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=false
app.seed.enabled=${APP_SEED_ENABLED:true}

# ===============================
# TOMCAT & MULTIPART MAX POST / PAYLOAD SIZE (50MB)
# ===============================
server.tomcat.max-http-form-post-size=52428800
server.tomcat.max-swallow-size=52428800
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=${PORT:8081}
server.address=0.0.0.0

# ===============================
# DISABLE H2 CONSOLE
# ===============================
spring.h2.console.enabled=false